# Generated by Django 5.2.10 on 2026-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
    ]
