# Generated by Django 5.2.10 on 2026-02-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_produk_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='gambar',
        ),
    ]
